/**
 * Security headers for the ONE route the assets binding never touches.
 *
 * `/` is the site's only non-prerendered route (step 7, so the live strip can
 * read its snapshot from KV per request). Its response is generated by the
 * Worker, so it never passes through public/_headers — that file is applied by
 * the assets binding, and the assets binding is not in this request's path.
 *
 * The reverse is also true, which is why both exist: for a PRERENDERED route
 * this middleware runs at BUILD time, and a header set on a response that is
 * about to be written to disk as a static file simply disappears. Middleware
 * cannot secure the static pages; _headers cannot secure `/`.
 *
 * KEEP THE TWO LISTS IN STEP. They are the same headers in two syntaxes, and
 * nothing in the build compares them — a drift is silent, and it is silent in
 * the worst direction, because the page most likely to be linked and framed is
 * the front door. The check is a curl of `/` against `/about/`; it is written
 * out in ../README.md.
 *
 * WHY NOT A CLOUDFLARE TRANSFORM RULE, which would cover both in one place:
 * because it would be invisible here. That is exactly the trap robots.txt fell
 * into — a dashboard setting silently changing what the domain serves while the
 * repo, which is meant to be the receipt, said something else.
 *
 * nosniff is absent on purpose: Cloudflare's "No-Sniff Header" toggle already
 * serves it zone-wide. See the note in public/_headers, including what to do if
 * HSTS is ever turned off, since the two share one panel.
 */
import { defineMiddleware } from 'astro:middleware';

/** Mirror of the `/*` block in public/_headers. Change both or neither. */
const SECURITY_HEADERS: Record<string, string> = {
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'X-Frame-Options': 'DENY',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=(), usb=()',
};

/**
 * `/` was sending NO Cache-Control at all (found 2026-09-05, while adding cache
 * rules to _headers). A response with no freshness information invites heuristic
 * caching, and this is the one route on the site that must never be served stale:
 * it exists solely so four values can be current.
 *
 * The failure that makes this worth a header rather than a shrug is specific. The
 * strip's stamp is rendered at REQUEST time and compares the snapshot's date to
 * today's, so it can say "cached yesterday 15:33" instead of "cached 15:33" — the
 * fix in commit fdcff79. A page held in a browser cache across midnight renders
 * that comparison with the wrong "today" and quietly reintroduces the same bug,
 * with no server involved and nothing to see in a log.
 *
 * Same value the static pages already carry, so the whole site is consistent:
 * revalidate every time, and a 304 still costs only a round trip.
 */
const NO_STALE = 'public, max-age=0, must-revalidate';

export const onRequest = defineMiddleware(async (_context, next) => {
  const response = await next();

  /* Some responses (redirects, and anything already streamed) can carry
     immutable headers. Setting into a guarded Headers throws, and a throw here
     would 500 the front door over a hardening measure — so this fails open and
     leaves a trace in the Worker log rather than taking the page down. */
  try {
    for (const [name, value] of Object.entries(SECURITY_HEADERS)) {
      response.headers.set(name, value);
    }
    /* Only for a response this middleware actually reaches at request time, and
       only if nothing upstream has already decided — static assets get their
       Cache-Control from _headers and must not be overridden here. */
    if (!response.headers.has('Cache-Control')) {
      response.headers.set('Cache-Control', NO_STALE);
    }
  } catch (err) {
    console.error('middleware: could not set security headers', err);
  }

  return response;
});
